// <auto-generated />
using System;
using EduGuardProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace EduGuardProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "app_role", "app_role", new[] { "STUDENT", "LECTURER", "SCHOOL_ADMIN", "SUPER_ADMIN", "student", "lecturer", "school_admin", "super_admin" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "attendance_method", "attendance_method", new[] { "AI", "MANUAL" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "attendance_status", "attendance_status", new[] { "PRESENT", "ABSENT", "LATE", "EXCUSED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "aal_level", new[] { "aal1", "aal2", "aal3" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "code_challenge_method", new[] { "s256", "plain" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "factor_status", new[] { "unverified", "verified" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "factor_type", new[] { "totp", "webauthn", "phone" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_authorization_status", new[] { "pending", "approved", "denied", "expired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_client_type", new[] { "public", "confidential" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_registration_type", new[] { "dynamic", "manual" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_response_type", new[] { "code" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "one_time_token_type", new[] { "confirmation_token", "reauthentication_token", "recovery_token", "email_change_token_new", "email_change_token_current", "phone_change_token" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "billing_model_enum", "billing_model", new[] { "MONTHLY", "YEARLY" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "biometric_req_status", "biometric_req_status", new[] { "PENDING", "APPROVED", "REJECTED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enrollment_status", "enrollment_status", new[] { "ACTIVE", "DROPPED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "exam_slot_status", "exam_slot_status", new[] { "SCHEDULED", "IN_PROGRESS", "COMPLETED", "CANCELLED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "institution_status", "institution_status", new[] { "ACTIVE", "INACTIVE", "SUSPENDED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_channel", "notification_channel", new[] { "PUSH", "EMAIL", "DASHBOARD" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_type", "notification_type", new[] { "LOW_BALANCE_ALERT", "ATTENDANCE_SESSION_STARTED", "EXAM_REMINDER", "VIOLATION_DETECTED", "BIOMETRIC_REQUEST_STATUS", "SERVICE_SUSPENDED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "participation_status", "participation_status", new[] { "JOINED", "SUBMITTED", "DISQUALIFIED", "ABSENT", "LEFT" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "pricing_service_type", "pricing_service_type", new[] { "attendance_unit", "proctoring_per_hour" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "realtime", "action", new[] { "INSERT", "UPDATE", "DELETE", "TRUNCATE", "ERROR" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "realtime", "equality_op", new[] { "eq", "neq", "lt", "lte", "gt", "gte", "in" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "reference_type_enum", "reference_type_enum", new[] { "INSTITUTION", "ATTENDANCE_SESSION", "EXAM_SLOT", "TRANSACTION" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "session_status", "session_status", new[] { "IN_PROGRESS", "COMPLETED", "CANCELLED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "storage", "buckettype", new[] { "STANDARD", "ANALYTICS", "VECTOR" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "student_exam_record_status", "student_exam_record_status", new[] { "MARKED", "COMPLETED", "DELETED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "transaction_status", "transaction_status", new[] { "PENDING", "SUCCESS", "FAILED", "pending", "success", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "transaction_type", "transaction_type", new[] { "TOP_UP", "ATTENDANCE_FEE", "PROCTORING_FEE", "top_up", "attendance_fee", "proctoring_fee" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_status", "user_status", new[] { "ACTIVE", "BLOCKED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "violation_severity", "violation_severity", new[] { "WARNING", "SEVERE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "violation_type", "violation_type", new[] { "IMPERSONATION", "GAZE_DIVERSION", "MULTIPLE_FACES", "ABSENCE", "HEAD_TURN", "FACE_OBSTRUCTED", "TabSwitch", "WindowBlur", "ExitFullscreen" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "pg_stat_statements");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "uuid-ossp");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vault", "supabase_vault");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EduGuardProject.Models.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AdjustedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("adjusted_at");

                    b.Property<Guid?>("AdjustedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("adjusted_by");

                    b.Property<DateTime?>("CheckinAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checkin_at");

                    b.Property<double?>("ConfidenceScore")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence_score");

                    b.Property<AttendanceMethod>("Method")
                        .HasColumnType("attendance_method")
                        .HasColumnName("method");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("SnapshotPath")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("snapshot_path")
                        .HasComment("Bucket: attendance-snapshots");

                    b.Property<AttendanceStatus>("Status")
                        .HasColumnType("attendance_status")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("attendance_records_pkey");

                    b.HasIndex("AdjustedBy");

                    b.HasIndex(new[] { "SessionId", "StudentId" }, "attendance_records_session_id_student_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "StudentId" }, "idx_attendance_record_student");

                    b.ToTable("attendance_records", (string)null);
                });

            modelBuilder.Entity("EduGuardProject.Models.AttendanceSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BillingTransId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_trans_id");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid?>("ExamSlotId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<SessionStatus>("Status")
                        .HasColumnType("session_status")
                        .HasColumnName("status");

                    b.Property<int>("TotalRecognized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_recognized");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VideoPath")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("video_path")
                        .HasComment("Bucket: attendance-videos");

                    b.HasKey("Id")
                        .HasName("attendance_sessions_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ExamSlotId");

                    b.HasIndex(new[] { "BillingTransId" }, "attendance_sessions_billing_trans_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "ClassId" }, "idx_attendance_session_class");

                    b.ToTable("attendance_sessions", (string)null);
                });

            modelBuilder.Entity("EduGuardProject.Models.BiometricDatum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BioRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("bio_request_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FaceImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("face_image_url")
                        .HasComment("Bucket: biometric-faces");

                    b.Property<Vector>("FaceVector")
                        .HasColumnType("vector(128)")
                        .HasColumnName("face_vector");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_version")
                        .HasComment("AI model version used to generate embedding");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("biometric_data_pkey");

                    b.HasIndex("BioRequestId");

                    b.HasIndex(new[] { "FaceImageUrl" }, "idx_biometric_face_image");

                    b.HasIndex(new[] { "UserId" }, "ux_biometric_active")
                        .IsUnique()
                        .HasFilter("(is_active = true)");

                    b.ToTable("biometric_data", (string)null);
                });

            modelBuilder.Entity("EduGuardProject.Models.BiometricRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FrontImagePath")
                        .HasColumnType("text")
                        .HasColumnName("front_image_path");

                    b.Property<string>("LeftImagePath")
                        .HasColumnType("text")
                        .HasColumnName("left_image_path");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("RightImagePath")
                        .HasColumnType("text")
                        .HasColumnName("right_image_path");

                    b.Property<BiometricReqStatus>("Status")
                        .HasColumnType("biometric_req_status")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("biometric_requests_pkey");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("StudentId");

                    b.ToTable("biometric_requests", (string)null);
                });

            modelBuilder.Entity("EduGuardProject.Models.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("academic_year");

                    b.Property<string>("CourseCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("course_code");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("course_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("institution_id");

                    b.Property<Guid>("LecturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("lecturer_id");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("semester");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("classes_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "InstitutionId" }, "idx_classes_institution");

                    b.HasIndex(new[] { "LecturerId" }, "idx_classes_lecturer");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("EduGuardProject.Models.ClassEnrollment", b =>
                {
                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at")
                        .HasDefaultValueSql("now()");

                    b.Property<EnrollmentStatus>("Status")
                        .HasColumnType("enrollment_status")
                        .HasColumnName("status");

                    b.HasKey("ClassId", "StudentId")
                        .HasName("class_enrollments_pkey");

                    b.HasIndex("StudentId");

                    b.ToTable("class_enrollments", (string)null);
                });

            modelBuilder.Entity("EduGuardProject.Models.ContactRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactPersonName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_person_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("school_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("contact_requests");
                });

            modelBuilder.Entity("EduGuardProject.Models.ExamParticipation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ActualEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_end");

                    b.Property<DateTime?>("ActualStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_start");

                    b.Property<Guid?>("BillingTransId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_trans_id");

                    b.Property<string>("DisqualifiedReason")
                        .HasColumnType("text")
                        .HasColumnName("disqualified_reason");

                    b.Property<Guid>("ExamSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_slot_id");

                    b.Property<string>("IdentitySnapshotPath")
                        .HasColumnType("text")
                        .HasColumnName("identity_snapshot_path")
                        .HasComment("Bucket: exam-identity");

                    b.Property<string>("RecordingVideoPath")
                        .HasColumnType("text")
                        .HasColumnName("recording_video_path")
                        .HasComment("Bucket: exam-recordings");

                    b.Property<ParticipationStatus>("Status")
                        .HasColumnType("participation_status")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("exam_participations_pkey");

                    b.HasIndex(new[] { "BillingTransId" }, "exam_participations_billing_trans_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "ExamSlotId", "StudentId" }, "exam_participations_exam_slot_id_student_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "StudentId" }, "idx_exam_participation_student");

                    b.HasIndex(new[] { "RecordingVideoPath" }, "idx_exam_recording");

                    b.ToTable("exam_participations", (string)null);
                });

            modelBuilder.Entity("EduGuardProject.Models.ExamQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("audio_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<Guid>("ExamSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_slot_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<decimal>("Points")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("points")
                        .HasDefaultValueSql("1");

                    b.Property<string>("QuestionContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_content");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("question_type");

                    b.HasKey("Id")
                        .HasName("exam_questions_pkey");

                    b.HasIndex(new[] { "ExamSlotId" }, "idx_exam_questions_exam_slot");

                    b.ToTable("exam_questions", (string)null);
                });

            modelBuilder.Entity("EduGuardProject.Models.ExamSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("exam_name");

                    b.Property<int>("ExpectedDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("expected_duration_minutes");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<ExamSlotStatus>("Status")
                        .HasColumnType("exam_slot_status")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("exam_slots_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "ClassId" }, "idx_exam_slot_class");

                    b.ToTable("exam_slots", (string)null);
                });

            modelBuilder.Entity("EduGuardProject.Models.Institution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<BillingModel>("BillingModel")
                        .HasColumnType("billing_model_enum")
                        .HasColumnName("billing_model");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact_email");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<InstitutionStatus>("Status")
                        .HasColumnType("institution_status")
                        .HasColumnName("status");

                    b.Property<string>("SubDomain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sub_domain");

                    b.Property<DateTime?>("SubscriptionExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_expires_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("institutions_pkey");

                    b.HasIndex(new[] { "SubDomain" }, "institutions_sub_domain_key")
                        .IsUnique();

                    b.ToTable("institutions", (string)null);
                });

            modelBuilder.Entity("EduGuardProject.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<ReferenceTypeEnum?>("ReferenceType")
                        .HasColumnType("reference_type_enum")
                        .HasColumnName("reference_type");

                    b.Property<NotificationChannel>("SentVia")
                        .HasColumnType("notification_channel")
                        .HasColumnName("sent_via");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<NotificationType>("Type")
                        .HasColumnType("notification_type")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("notifications_pkey");

                    b.HasIndex(new[] { "UserId" }, "idx_notifications_user");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("EduGuardProject.Models.PricingConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<PricingServiceType>("ServiceType")
                        .HasColumnType("pricing_service_type")
                        .HasColumnName("service_type");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price")
                        .HasComment("Pricing in VND");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pricing_configs_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("pricing_configs", (string)null);
                });

            modelBuilder.Entity("EduGuardProject.Models.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_correct");

                    b.Property<string>("OptionContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("option_content");

                    b.Property<string>("OptionLabel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("option_label");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.HasKey("Id")
                        .HasName("question_options_pkey");

                    b.HasIndex(new[] { "QuestionId" }, "idx_question_options_question");

                    b.ToTable("question_options", (string)null);
                });

            modelBuilder.Entity("EduGuardProject.Models.StudentExamRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("ExamRecord")
                        .HasColumnType("jsonb")
                        .HasColumnName("exam_record");

                    b.Property<Guid>("ExamSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_slot_id");

                    b.Property<decimal?>("FinalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("final_score");

                    b.Property<StudentExamRecordStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("student_exam_record_status")
                        .HasDefaultValue(StudentExamRecordStatus.Marked)
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id")
                        .HasComment("Must reference a users.id whose role is STUDENT.");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id")
                        .HasName("student_exam_records_pkey");

                    b.HasIndex(new[] { "ExamSlotId" }, "idx_student_exam_records_exam_slot");

                    b.HasIndex(new[] { "StudentId" }, "idx_student_exam_records_student");

                    b.ToTable("student_exam_records", (string)null);
                });

            modelBuilder.Entity("EduGuardProject.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("PricingConfigId")
                        .HasColumnType("uuid")
                        .HasColumnName("pricing_config_id");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<TransactionStatus>("Status")
                        .HasColumnType("transaction_status")
                        .HasColumnName("status");

                    b.Property<TransactionType>("Type")
                        .HasColumnType("transaction_type")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VnpayRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vnpay_ref");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("transactions_pkey");

                    b.HasIndex("PricingConfigId");

                    b.HasIndex(new[] { "WalletId" }, "idx_transactions_wallet");

                    b.HasIndex(new[] { "VnpayRef" }, "transactions_vnpay_ref_key")
                        .IsUnique();

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("EduGuardProject.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<Guid?>("InstitutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("institution_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<AppRole>("Role")
                        .HasColumnType("app_role")
                        .HasColumnName("role");

                    b.Property<UserStatus>("Status")
                        .HasColumnType("user_status")
                        .HasColumnName("status");

                    b.Property<string>("StudentCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("student_code");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "InstitutionId" }, "idx_users_institution");

                    b.HasIndex(new[] { "InstitutionId", "StudentCode" }, "ux_student_code_per_institution")
                        .IsUnique()
                        .HasFilter("(student_code IS NOT NULL)");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EduGuardProject.Models.ViolationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double?>("AiConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("ai_confidence");

                    b.Property<string>("EvidencePath")
                        .HasColumnType("text")
                        .HasColumnName("evidence_path")
                        .HasComment("Bucket: exam-evidence");

                    b.Property<bool>("IsReviewed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_reviewed");

                    b.Property<Guid>("ParticipationId")
                        .HasColumnType("uuid")
                        .HasColumnName("participation_id");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<ViolationSeverity>("severity")
                        .HasColumnType("violation_severity")
                        .HasColumnName("severity");

                    b.Property<ViolationType>("violationType")
                        .HasColumnType("violation_type")
                        .HasColumnName("violation_type");

                    b.HasKey("Id")
                        .HasName("violation_logs_pkey");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex(new[] { "ParticipationId" }, "idx_violation_participation");

                    b.ToTable("violation_logs", (string)null);
                });

            modelBuilder.Entity("EduGuardProject.Models.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency")
                        .HasDefaultValueSql("'VND'::character varying");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("institution_id");

                    b.Property<DateTime?>("LowBalanceAlertSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("low_balance_alert_sent_at");

                    b.Property<decimal>("LowBalanceThreshold")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("low_balance_threshold")
                        .HasDefaultValueSql("50000");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("wallets_pkey");

                    b.HasIndex(new[] { "InstitutionId" }, "wallets_institution_id_key")
                        .IsUnique();

                    b.ToTable("wallets", (string)null);
                });

            modelBuilder.Entity("EduGuardProject.Models.AttendanceRecord", b =>
                {
                    b.HasOne("EduGuardProject.Models.User", "AdjustedByNavigation")
                        .WithMany("AttendanceRecordAdjustedByNavigations")
                        .HasForeignKey("AdjustedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("attendance_records_adjusted_by_fkey");

                    b.HasOne("EduGuardProject.Models.AttendanceSession", "Session")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("attendance_records_session_id_fkey");

                    b.HasOne("EduGuardProject.Models.User", "Student")
                        .WithMany("AttendanceRecordStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("attendance_records_student_id_fkey");

                    b.Navigation("AdjustedByNavigation");

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduGuardProject.Models.AttendanceSession", b =>
                {
                    b.HasOne("EduGuardProject.Models.Transaction", "BillingTrans")
                        .WithOne("AttendanceSession")
                        .HasForeignKey("EduGuardProject.Models.AttendanceSession", "BillingTransId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("attendance_sessions_billing_trans_id_fkey");

                    b.HasOne("EduGuardProject.Models.Class", "Class")
                        .WithMany("AttendanceSessions")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("attendance_sessions_class_id_fkey");

                    b.HasOne("EduGuardProject.Models.User", "CreatedByNavigation")
                        .WithMany("AttendanceSessions")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("attendance_sessions_created_by_fkey");

                    b.HasOne("EduGuardProject.Models.ExamSlot", "ExamSlot")
                        .WithMany()
                        .HasForeignKey("ExamSlotId");

                    b.Navigation("BillingTrans");

                    b.Navigation("Class");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ExamSlot");
                });

            modelBuilder.Entity("EduGuardProject.Models.BiometricDatum", b =>
                {
                    b.HasOne("EduGuardProject.Models.BiometricRequest", "BioRequest")
                        .WithMany("BiometricData")
                        .HasForeignKey("BioRequestId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("biometric_data_bio_request_id_fkey");

                    b.HasOne("EduGuardProject.Models.User", "User")
                        .WithOne("BiometricDatum")
                        .HasForeignKey("EduGuardProject.Models.BiometricDatum", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("biometric_data_user_id_fkey");

                    b.Navigation("BioRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduGuardProject.Models.BiometricRequest", b =>
                {
                    b.HasOne("EduGuardProject.Models.User", "ApprovedByNavigation")
                        .WithMany("BiometricRequestApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("biometric_requests_approved_by_fkey");

                    b.HasOne("EduGuardProject.Models.User", "Student")
                        .WithMany("BiometricRequestStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("biometric_requests_student_id_fkey");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduGuardProject.Models.Class", b =>
                {
                    b.HasOne("EduGuardProject.Models.User", "CreatedByNavigation")
                        .WithMany("ClassCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("classes_created_by_fkey");

                    b.HasOne("EduGuardProject.Models.Institution", "Institution")
                        .WithMany("Classes")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("classes_institution_id_fkey");

                    b.HasOne("EduGuardProject.Models.User", "Lecturer")
                        .WithMany("ClassLecturers")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("classes_lecturer_id_fkey");

                    b.HasOne("EduGuardProject.Models.User", "UpdatedByNavigation")
                        .WithMany("ClassUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("classes_updated_by_fkey");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Institution");

                    b.Navigation("Lecturer");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("EduGuardProject.Models.ClassEnrollment", b =>
                {
                    b.HasOne("EduGuardProject.Models.Class", "Class")
                        .WithMany("ClassEnrollments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("class_enrollments_class_id_fkey");

                    b.HasOne("EduGuardProject.Models.User", "Student")
                        .WithMany("ClassEnrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("class_enrollments_student_id_fkey");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduGuardProject.Models.ExamParticipation", b =>
                {
                    b.HasOne("EduGuardProject.Models.Transaction", "BillingTrans")
                        .WithOne("ExamParticipation")
                        .HasForeignKey("EduGuardProject.Models.ExamParticipation", "BillingTransId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("exam_participations_billing_trans_id_fkey");

                    b.HasOne("EduGuardProject.Models.ExamSlot", "ExamSlot")
                        .WithMany("ExamParticipations")
                        .HasForeignKey("ExamSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("exam_participations_exam_slot_id_fkey");

                    b.HasOne("EduGuardProject.Models.User", "Student")
                        .WithMany("ExamParticipations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("exam_participations_student_id_fkey");

                    b.Navigation("BillingTrans");

                    b.Navigation("ExamSlot");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduGuardProject.Models.ExamQuestion", b =>
                {
                    b.HasOne("EduGuardProject.Models.ExamSlot", "ExamSlot")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("exam_questions_exam_slot_id_fkey");

                    b.Navigation("ExamSlot");
                });

            modelBuilder.Entity("EduGuardProject.Models.ExamSlot", b =>
                {
                    b.HasOne("EduGuardProject.Models.Class", "Class")
                        .WithMany("ExamSlots")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("exam_slots_class_id_fkey");

                    b.HasOne("EduGuardProject.Models.User", "CreatedByNavigation")
                        .WithMany("ExamSlots")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("exam_slots_created_by_fkey");

                    b.Navigation("Class");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("EduGuardProject.Models.Notification", b =>
                {
                    b.HasOne("EduGuardProject.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("notifications_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduGuardProject.Models.PricingConfig", b =>
                {
                    b.HasOne("EduGuardProject.Models.User", "CreatedByNavigation")
                        .WithMany("PricingConfigCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("pricing_configs_created_by_fkey");

                    b.HasOne("EduGuardProject.Models.User", "UpdatedByNavigation")
                        .WithMany("PricingConfigUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("pricing_configs_updated_by_fkey");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("EduGuardProject.Models.QuestionOption", b =>
                {
                    b.HasOne("EduGuardProject.Models.ExamQuestion", "Question")
                        .WithMany("QuestionOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("question_options_question_id_fkey");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("EduGuardProject.Models.StudentExamRecord", b =>
                {
                    b.HasOne("EduGuardProject.Models.ExamSlot", "ExamSlot")
                        .WithMany("StudentExamRecords")
                        .HasForeignKey("ExamSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("student_exam_records_exam_slot_id_fkey");

                    b.HasOne("EduGuardProject.Models.User", "Student")
                        .WithMany("StudentExamRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("student_exam_records_student_id_fkey");

                    b.Navigation("ExamSlot");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduGuardProject.Models.Transaction", b =>
                {
                    b.HasOne("EduGuardProject.Models.PricingConfig", "PricingConfig")
                        .WithMany("Transactions")
                        .HasForeignKey("PricingConfigId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("transactions_pricing_config_id_fkey");

                    b.HasOne("EduGuardProject.Models.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("transactions_wallet_id_fkey");

                    b.Navigation("PricingConfig");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("EduGuardProject.Models.User", b =>
                {
                    b.HasOne("EduGuardProject.Models.Institution", "Institution")
                        .WithMany("Users")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("users_institution_id_fkey");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("EduGuardProject.Models.ViolationLog", b =>
                {
                    b.HasOne("EduGuardProject.Models.ExamParticipation", "Participation")
                        .WithMany("ViolationLogs")
                        .HasForeignKey("ParticipationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("violation_logs_participation_id_fkey");

                    b.HasOne("EduGuardProject.Models.User", "ReviewedByNavigation")
                        .WithMany("ViolationLogs")
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("violation_logs_reviewed_by_fkey");

                    b.Navigation("Participation");

                    b.Navigation("ReviewedByNavigation");
                });

            modelBuilder.Entity("EduGuardProject.Models.Wallet", b =>
                {
                    b.HasOne("EduGuardProject.Models.Institution", "Institution")
                        .WithOne("Wallet")
                        .HasForeignKey("EduGuardProject.Models.Wallet", "InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("wallets_institution_id_fkey");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("EduGuardProject.Models.AttendanceSession", b =>
                {
                    b.Navigation("AttendanceRecords");
                });

            modelBuilder.Entity("EduGuardProject.Models.BiometricRequest", b =>
                {
                    b.Navigation("BiometricData");
                });

            modelBuilder.Entity("EduGuardProject.Models.Class", b =>
                {
                    b.Navigation("AttendanceSessions");

                    b.Navigation("ClassEnrollments");

                    b.Navigation("ExamSlots");
                });

            modelBuilder.Entity("EduGuardProject.Models.ExamParticipation", b =>
                {
                    b.Navigation("ViolationLogs");
                });

            modelBuilder.Entity("EduGuardProject.Models.ExamQuestion", b =>
                {
                    b.Navigation("QuestionOptions");
                });

            modelBuilder.Entity("EduGuardProject.Models.ExamSlot", b =>
                {
                    b.Navigation("ExamParticipations");

                    b.Navigation("ExamQuestions");

                    b.Navigation("StudentExamRecords");
                });

            modelBuilder.Entity("EduGuardProject.Models.Institution", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Users");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("EduGuardProject.Models.PricingConfig", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("EduGuardProject.Models.Transaction", b =>
                {
                    b.Navigation("AttendanceSession");

                    b.Navigation("ExamParticipation");
                });

            modelBuilder.Entity("EduGuardProject.Models.User", b =>
                {
                    b.Navigation("AttendanceRecordAdjustedByNavigations");

                    b.Navigation("AttendanceRecordStudents");

                    b.Navigation("AttendanceSessions");

                    b.Navigation("BiometricDatum");

                    b.Navigation("BiometricRequestApprovedByNavigations");

                    b.Navigation("BiometricRequestStudents");

                    b.Navigation("ClassCreatedByNavigations");

                    b.Navigation("ClassEnrollments");

                    b.Navigation("ClassLecturers");

                    b.Navigation("ClassUpdatedByNavigations");

                    b.Navigation("ExamParticipations");

                    b.Navigation("ExamSlots");

                    b.Navigation("Notifications");

                    b.Navigation("PricingConfigCreatedByNavigations");

                    b.Navigation("PricingConfigUpdatedByNavigations");

                    b.Navigation("StudentExamRecords");

                    b.Navigation("ViolationLogs");
                });

            modelBuilder.Entity("EduGuardProject.Models.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
